name: 'tool-versions-action'
description: 'Parse tool versions into environment variables'
author: 'AGS4NO'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  file:
    description: 'Path to tool versions file'
    required: true
    default: '.tool-versions'

outputs:
  golang-version:
    description: 'The version of Go (dynamic)'
  nodejs-version:
    description: 'The version of Node.js (dynamic)'
  ruby-version:
    description: 'The version of Ruby (dynamic)'

runs:
  using: node20
  main: dist/index.js
