name: 'tool-versions-action'
description: 'Parse tool versions into environment variables'
author: 'AGS4NO'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  file:
    description: 'Path to tool versions file'
    required: true
    default: '.tool-versions'

runs:
  using: node20
  main: dist/index.js
